dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'infra'
       orgId: 1
       folder: 'infra'
       type: file
       disableDeletion: false
       editable: true
       options:
         path:  /var/lib/grafana/dashboards/infra
dashboards: 
  infra:
    kubernetes-overview:
      gnetId: 21410
      datasource: Prometheus
      revision: 2
    node-exporter-full:
      gnetId: 1860
      revision: 37
      datasource: Prometheus
    kubernetes-service-logs:
      gnetId: 15141
      datasource: loki
    jaeger-collector:
      gnetId: 8472
      datasource: Prometheus
    ingress-nginx:
      gnetId: 9614
      datasource: Prometheus

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: loki
      type: loki
      url: http://loki-gateway
    - name: Prometheus 
      type: prometheus
      isDefault: true
      url: http://kube-prometheus-prometheus:9090
    - name: Jaeger
      type: Jaeger
      url: http://jaeger-query

tolerations:
- key: "node-role"
  operator: "Equal"
  value: "infra"
  effect: "NoSchedule"
affinity: 
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role
          operator: In
          values:
          - infra
ingress:
  enabled: true
  tls:
    - secretName: grafana-tls
      hosts:
       - grafana.evgsh.space
  hosts:
    - grafana.evgsh.space
  ingressClassName: nginx
  annotations:
     cert-manager.io/cluster-issuer: yc-clusterissuer
