name: Terraform destroy
run-name: ${{ github.actor }} destroy  plan for terraform 🚀
on:
  workflow_dispatch:
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2 
    - uses: addnab/docker-run-action@v3
      with:
        registry: gcr.io
        image: ghcr.io/opentofu/opentofu:latest
        options: -v ${{ github.workspace }}:/workdir -e YC_STORAGE_ACCESS_KEY=${{ secrets.YC_STORAGE_ACCESS_KEY }} -e YC_CLOUD_ID=${{ secrets.YC_CLOUD_ID }} -e YC_FOLDER_ID=${{ secrets.YC_FOLDER_ID }} -e YC_STORAGE_SECRET_KEY=${{ secrets.YC_STORAGE_SECRET_KEY }} -e YC_TOKEN=${{ secrets.YC_TOKEN }} -e TF_VAR_folder_id=${{ secrets.YC_FOLDER_ID }}
        run: |
             cd /workdir/
             tofu init -backend-config="access_key=$YC_STORAGE_ACCESS_KEY" -backend-config="secret_key=$YC_STORAGE_SECRET_KEY"
             tofu init -upgrade
             tofu destroy -input=false -compact-warnings -auto-approve -var-file="my.tfvars" || true
